groups:
    examplegroupone:
    - exampleworldtwo
    examplegrouptwo:
    - exampleworldtwo
    - exampleworldthree
donotifications: true
domiimport: false
dostats: false
outputtimertoconsole: true
saveinterval: 0