# A "group" is a collection of worlds which will share an inventory.
#  In this example there are two groups, a creative and a survival group
#  Each group has an overworld and a nether, which will share an inventory

# Inventory switching examples
# Scenarios when the inventory will not switch:
#  creative_overworld to creative_nether
#  survival_nether to survival_overworld
#  survival_end to survival_overworld
# Scenarios when the inventory will switch:
#   creative_overworld to survival_end
#   survival_nether to creative_nether

# If "donotifications" is set to false you won't get inventory switching notifications in the console
# Set "domiimport" to true to make WorldInventories attempt to import MultiInv data
#  Automatically sets itself to false when an attempt is made
# Set "dostats" to true to make hearts, food level, experience and such track with inventory
# If a save interval is specified, set "outputtimertoconsole" to false to stop it from outputting to the console
# Set "saveinterval" to anything above 30 to make inventories/stats save automatically every x seconds
# Set "loadinvonlogin" to true to make the plugin load the player's inventory on login no matter where they spawn

groups:
    creativegroup:
    - creative_overworld
    - creative_nether
    survivalgroup:
    - survival_overworld
    - survival_nether
    - survival_end

donotifications: true
domiimport: false
dostats: false
outputtimertoconsole: true
saveinterval: 0
loadinvonlogin: true